# Generated by Django 6.0.3 on 2026-03-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_code',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True, verbose_name='Короткий код'),
        ),
    ]
